sudo: required
services:
  - docker

before_install:
  - docker build -t smagin07/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run smagin07/react-test npm test -- --coverage

after_success:
  - docker build -t smagin07/multi-client ./client
  - docker build -t smagin07/multi-nginx ./nginx
  - docker build -t smagin07/multi-server ./server
  - docker build -t smagin07/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
  - docker push smagin07/multi-client
  - docker push smagin07/multi-nginx
  - docker push smagin07/multi-server
  - docker push smagin07/multi-worker
