sudo: required
services:
  - docker

before_install:
  - docker build -t sm00g15/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sm00g15/react-test npm test -- --coverage

after_success:
  - docker build -t sm00g15/multi-client ./client
  - docker build -t sm00g15/multi-nginx ./nginx
  - docker build -t sm00g15/multi-server ./server
  - docker build -t sm00g15/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
  - docker push sm00g15/multi-client
  - docker push sm00g15/multi-nginx
  - docker push sm00g15/multi-server
  - docker push sm00g15/multi-worker
